# config/packages/security.yaml

security:
    # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
    password_hashers:
        App\Entity\User: 
            algorithm: bcrypt
            cost: 12        
            #algorithm: plaintext

    # https://symfony.com/doc/current/security/authenticator_manager.html
    enable_authenticator_manager: true

    role_hierarchy:
        ROLE_ADMIN: [
               #ROLE_SUPER_ADMIN #ACCESO A TODO EL SISTEMA
               #ROLE_USER,
               #ROLE_SONATA_ADMIN, 
               ROLE_ADMIN_USER_ALL,               
               ROLE_ADMIN_CLIENTE_ALL,
               ROLE_ADMIN_PROVEEDOR_ALL,
               ROLE_ADMIN_PRODUCTO_ALL,
               ROLE_ADMIN_LOTE_ALL,
               ROLE_ADMIN_CATEGORIA_ALL,
               ROLE_ADMIN_STOCK_ALL,
               ROLE_ADMIN_MOVIMIENTO_STOCK_ALL,
               ROLE_ADMIN_VENTA_ALL,
               ROLE_ADMIN_DETALLE_VENTA_ALL,
               ROLE_ADMIN_COBRO_CLIENTE_ALL,
               ROLE_ADMIN_CUENTA_CORRIENTE_CLIENTE_ALL,
               ROLE_ADMIN_CAJA_ALL
               ]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        users:
            id: App\Security\UserProvider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        admin:
            pattern: ^/admin
            provider: users
            login_throttling:
                max_attempts: 3 # per minute ...
                interval: '15 minutes'
            form_login:
                login_path: admin_login
                check_path: admin_login
                enable_csrf: true
            logout:
                path: admin_logout
                target: sonata_admin_dashboard
            #custom_authenticators:
            #    - App\Security\AdminLoginAuthenticator

        main:
            lazy: true
            provider: users

    access_control:
        - { path: '^/admin/login$', roles: PUBLIC_ACCESS }
        - { path: '^/admin/logout$', roles: PUBLIC_ACCESS }
        - { path: '^/admin/', roles: [ROLE_ADMIN, ROLE_SONATA_ADMIN] }
        - { path: '^/.*', roles: PUBLIC_ACCESS }

#when@test:
#    security:
#        password_hashers:
#            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
#                algorithm: auto
#                cost: 4 # Lowest possible value for bcrypt
#                time_cost: 3 # Lowest possible value for argon
#                memory_cost: 10 # Lowest possible value for argon
