sonata_admin:
    title: 'Sistema'
    title_logo: 'img/logo/logo.png'
    dashboard:
        blocks:
            - { type: sonata.admin.block.admin_list, position: left }

    security:
        handler: sonata.admin.security.handler.role

    templates:
        layout: 'standard_layout.html.twig'

sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
